@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khanhpham.tothemoon.datagen.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;