@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khanhtypo.tothemoon.multiblock.blackstonefurnace.ioparts.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;