@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khanhtypo.tothemoon.common.machine.electricalsmelter;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;