@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khanhtypo.tothemoon.registration.bases;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;