@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khanhtypo.tothemoon.serverdata.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;