@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.khanhtypo.tothemoon.common.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;